// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int countMoreThanHalf = 0;
		for (int i = 0; i < n; i++) {
			if (Math.random() > 0.5)	countMoreThanHalf++;
		}
		System.out.println("> 0.5: " + countMoreThanHalf + " times");
		System.out.println("<= 0.5: " + (n - countMoreThanHalf) + " times");
		if (0 < countMoreThanHalf && countMoreThanHalf < n) {
			double ratio = ((double) countMoreThanHalf) / ((double) (n - countMoreThanHalf));

			System.out.println("Ratio: " + ratio);
		}		
	}
}
